FROM node:18-alpine AS builder

WORKDIR /app

# Enable pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy and install deps
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Copy all source code
COPY . .

# Build static (next.config.mjs có `output: 'export'`)
RUN pnpm build

# Stage copy ra host
FROM alpine:latest AS export
WORKDIR /export
COPY --from=builder /app/out ./course
