version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    container_name: multi-site-caddy
    ports:
      - "8080:8080"
    volumes:
      - ./out:/srv:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
